### ISSUE TITLE
HTML anchors data seems to be broken

### ISSUE THREAD

**Issue by sidvishnoi** [speced/bikeshed-data#9]
https://github.com/tabatkins/bikeshed-data/commit/6bd7031f849ac147a15a68994b49911dfed6b8a0 appears bring some breaking changes. Lots of anchors data (I've observed only HTML spec) have changed for some reason that I'm not yet understanding (no changes in HTML spec source).

Did something change in Shepherd's parsing? I've used a backup in ReSpec to handle the present breakage.

**Comment by sidvishnoi** [comment]
http://hg.csswg.org/dev/specification/rev/d6e5dc2618c8 seems a bit related. cc: @plinss

**Comment by marcoscaceres** [comment]
Indeed, HTML has `<pre><code class=idl>`
![Screen Shot 2020-08-24 at 8 42 47 pm](https://user-images.githubusercontent.com/870154/91036306-713ccd80-e64a-11ea-9d6b-604a1449f792.png)

**Comment by plinss** [comment]
Yeah, my bad. I reverted that change.

Bikeshed is generating `<code class="idl>` for references to methods and other IDL entities, this was causing Shepherd's parser to try to parse them all as IDL, and generating a lot of errors. I forgot that the HTML spec puts the 'idl' class on the `<code>` rather than the `<pre>` as Bikeshed specs do.

I'd still like to get rid of the errors in Shepherd (and I'm concerned that doing extra IDL parsing may confuse valid IDL anchors). This would require either all specs to use `<pre class="idl">` or Bikeshed (and possibly ReSpec) to stop generating `<code class="idl">`, or some other way of differentiating them.

I suppose if HTML is consistent about always using `<pre><code class="idl">` I can detect that, and only process `<code class="idl">` inside a `<pre>`. Do we know if that's ensured?

**Comment by sidvishnoi** [comment]
If we ask specs to use updated tooling with the behavior we desire, it will take some time to republish all the specs, and all might not even agree to do so. Might be better to special case HTML/WHATWG specs instead if needed.

> I suppose if HTML is consistent about always using `<pre><code class="idl">` I can detect that, and only process `<code class="idl">` inside a `<pre>`. Do we know if that's ensured?

Running following on the HTML spec (tested on single-page version, and some multipage ones) shows it is consistent about it:
```js
$$("code.idl").length == $$("code.idl").filter(el => el.parentElement.localName === "pre").length
```

That is, there are no `code.idl` outside `<pre>`.

At https://infra.spec.whatwg.org/ and https://w3c.github.io/ambient-light/ (Bikeshed):
```js
$$("code.idl").length > $$("code.idl").filter(el => el.parentElement.localName === "pre").length
$$("code.idl > a").length == $$("code.idl").length
$$("code.idl *:only-child").length ==  $$("code.idl").length
// only code.idl outside a pre contain a single link
```

So, I think it's safe to process `pre > code.idl` and `pre.idl` only.

**Comment by plinss** [comment]
Cool, thanks for looking at that for me @sidvishnoi. I'll make the change to Shepherd's parser.
